# 06.1-异步编程-Promise 基础

## 一 异步编程与回调地狱

同步行为和异步行为的对立统一是计算机科学的一个基本概念。特别是在 JavaScript 这种单线程事件循环模型中，同步操作与异步操作更是代码所要依赖的核心机制。异步行为是为了优化因计算量大而时间长的操作，这样可以在等待其他操作完成的同时运行其他指令。

> 同步：对应内存中的顺序执行的指令，每条指令会严格按照出现顺序执行，程序执行的每一步都可以推断出程序执行的状态
> 异步：类似于系统中断，即当前进程外部的实体可以触发代码执行。如果代码要访问一些高延迟的资源，比如向远程服务器发送请求并等待响应，那么就会出现长时间的等待。

看一个基础的异步编程示例：

```js
function double(value) {
  setTimeout(() => {
    console.log(value)
  }, 1000)
}

// 先打印 last，再打印数值
double(3)
console.log('last')
```

异步行为虽然解决了高延迟资源访问时的等待问题，但是在实际开发中，会带来相当的不便，产生回调地狱的代码在可维护性上是相当差的：

```js
XHR.onreadystatechange = function(){
    if(){
        XHR2.onreadystatechange = function(){

            if(){

                XHR2.onreadystatechange = function(){

                    if(){
                        XHR2.onreadystatechange = function(){

                        }
                    }
                }
            }
        }
    }
}
```

异步的失败处理也同样不方便，因为要考虑成功回调、失败回调

```js
function double(value, success, failure) {
  setTimeout(() => {
    try {
      if (typeof value !== 'number') {
        throw 'Must provide number as first argument'
      }
      success(2 * value)
    } catch (e) {
      failure(e)
    }
  }, 1000)
}

const successCallback = (x) => console.log(`Success: ${x}`)
const failureCallback = (e) => console.log(`Failure: ${e}`)
double(3, successCallback, failureCallback) // Success: 6（大约 1000 毫秒之后）
double('b', successCallback, failureCallback) // Failure: Must provide number as first argument（大约 1000 毫秒之后）
```

异步的优化方案很多，包括将回调函数命名、全部采用函数名方式调用、优化代码结构、Node 中的第三方库 Async 等，但是这些在书写上都是治标不治本。

ECMAScript 提出了三个解决方案：

- Promise 方案：基本的异步解决方案
- generator 生成器方案：ES6 过渡方案
- async/await 方案：ES7 提出的方案，配合 Promise 能够完美解决 JS 异步问题

## 二 期约 Promise 对象

### 2.1 期约 Promise 基本概念

期约 Promise 名字最早起源于 1976 年，描述了一种异步程序的执行机制。到了 2010 年，CommonJS 实现的 Promises/A 规范开始流行。

ES6 对市面流行的第三方 Promise/A+ 规范提供了完善支持，即 Promise 引用类型。Promise 是现在异步编程的核心机制，得到了所有现代浏览器的支持。

Promise 类是一个实现了 Thenable 接口的对象，示例如下：

```js
// 构造函数必须传参，否则报错，一般该参数称为执行器 executor
// 传入的函数用来修改 Promise 的执行结果，正确与错误的结果分别位于 resolve、reject 中
let p = new Promise((resolve, reject) => {
  setTimeout(() => {
    // 模拟 ajax
    let err = null
    let data = { uid: 1001 }
    if (err) {
      reject('发生了错误：', null)
    }
    resolve(data)
  })
})

// 实例方法 then：用于处理状态改变后的业务
p.then(
  (data) => {
    console.log(data)
  },
  (err) => {
    console.log(err)
  }
)

// 输出结果：{ uid: 1001 }
```

从上看出，**期约的作用其实是抽象的表示了一个异步操作**。

### 2.2 实例方法 then()

Promise.prototype.then()方法接收两个可选的参数： onResolved 处理程序和 onRejected 处理程序，如果提供的话，则会在期约分别进入“兑现”和“拒绝”状态时执行：

```js
function onResolved(id) {
  setTimeout(console.log, 0, id, 'resolved')
}

function onRejected(id) {
  setTimeout(console.log, 0, id, 'rejected')
}

let p1 = new Promise((resolve, reject) => setTimeout(resolve, 3000))
let p2 = new Promise((resolve, reject) => setTimeout(reject, 3000))

p1.then(
  () => onResolved('p1'),
  () => onRejected('p1')
)

p2.then(
  () => onResolved('p2'),
  () => onRejected('p2')
)

//（ 3 秒后）
// p1 resolved
// p2 rejected
```

传给 then()的任何非函数类型的参数都会被静默忽略。如果想只提供 onRejected 参数，那就要在 onResolved 参数的位置上传入 undefined。这
样有助于避免在内存中创建多余的对象，对期待函数参数的类型系统也是一个交代。

### 2.3 实例方法 catch()

Promise.prototype.catch()方法用于给期约添加拒绝处理程序。这个方法只接收一个参数：onRejected 处理程序。事实上，这个方法就是一个语法糖，调用它就相当于调用 Promise.prototype.then(null, onRejected)。

```js
let p = Promise.reject()
let onRejected = function (e) {
  setTimeout(console.log, 0, 'rejected')
}
// 这两种添加拒绝处理程序的方式是一样的：
p.then(null, onRejected) // rejected
p.catch(onRejected) // rejected
```

Promise.prototype.catch()返回一个新的期约实例：

```js
let p1 = new Promise(() => {})
let p2 = p1.catch()
setTimeout(console.log, 0, p1) // Promise <pending>
setTimeout(console.log, 0, p2) // Promise <pending>
setTimeout(console.log, 0, p1 === p2) // false
```

then() 方法返回的仍然是一个 Promise 实例，所以可以使用 then 方法进行链式调用：

```js
let flag = false

// 在该函数内执行异步操作，并修改结果的状态值。
let p = new Promise(function (resolve, reject) {
  if (flag) {
    resolve('true...')
  } else {
    reject('false...')
  }
})

p.then((data) => {
  console.log('处理成功，结果为：', data)
}).catch((err) => {
  // 实例方法 catch：用于捕获错误
  console.log('处理失败，错误为：', err)
})
```

### 2.4 finally() 方法

Promise.prototype.finally()方法用于给期约添加 onFinally 处理程序，这个处理程序在期约转换为解决或拒绝状态时都会执行。这个方法可以避免 onResolved 和 onRejected 处理程序中出现冗余代码。但 onFinally 处理程序没有办法知道期约的状态是解决还是拒绝，所以这个方法主要用于添加清理代码。

```js
let p1 = Promise.resolve()
let p2 = Promise.reject()
let onFinally = function () {
  setTimeout(console.log, 0, 'Finally!')
}
p1.finally(onFinally) // Finally
p2.finally(onFinally) // Finally
```

Promise.prototype.finally()方法返回一个新的期约实例：

```js
let p1 = new Promise(() => {})
let p2 = p1.finally()
setTimeout(console.log, 0, p1) // Promise <pending>
setTimeout(console.log, 0, p2) // Promise <pending>
setTimeout(console.log, 0, p1 === p2) // false
```

这个新期约实例不同于 then()或 catch()方式返回的实例。因为 onFinally 被设计为一个状态无关的方法， 所以在大多数情况下它将表现为父期约的传递。对于已解决状态和被拒绝状态都是如此。

```js
let p1 = Promise.resolve('foo')

let p2 = p1.finally()
let p3 = p1.finally(() => undefined)
let p4 = p1.finally(() => {})
let p5 = p1.finally(() => Promise.resolve())
let p6 = p1.finally(() => 'bar')
let p7 = p1.finally(() => Promise.resolve('bar'))
let p8 = p1.finally(() => Error('qux'))
setTimeout(console.log, 0, p2) // Promise <resolved>: foo
setTimeout(console.log, 0, p3) // Promise <resolved>: foo
setTimeout(console.log, 0, p4) // Promise <resolved>: foo
setTimeout(console.log, 0, p5) // Promise <resolved>: foo
setTimeout(console.log, 0, p6) // Promise <resolved>: foo
setTimeout(console.log, 0, p7) // Promise <resolved>: foo
setTimeout(console.log, 0, p8) // Promise <resolved>: foo
```

如果返回的是一个待定的期约，或者 onFinally 处理程序抛出了错误（显式抛出或返回了一个拒绝期约），则会返回相应的期约（待定或拒绝），如下所示：

```js
// Promise.resolve()保留返回的期约
let p9 = p1.finally(() => new Promise(() => {}))
let p10 = p1.finally(() => Promise.reject())
// Uncaught (in promise): undefined
setTimeout(console.log, 0, p9) // Promise <pending>
setTimeout(console.log, 0, p10) // Promise <rejected>: undefined
let p11 = p1.finally(() => {
  throw 'baz'
})
// Uncaught (in promise) baz
setTimeout(console.log, 0, p11) // Promise <rejected>: baz]
```

返回待定期约的情形并不常见，这是因为只要期约一解决，新期约仍然会原样后传初始的期约：

```js
let p1 = Promise.resolve('foo')
// 忽略解决的值
let p2 = p1.finally(
  () => new Promise((resolve, reject) => setTimeout(() => resolve('bar'), 100))
)
setTimeout(console.log, 0, p2) // Promise <pending>
setTimeout(() => setTimeout(console.log, 0, p2), 200)
// 200 毫秒后：
// Promise <resolved>: foo
```

## 三 期约 Promise 状态

### 3.1 期约状态机

直接把一个期约实例传递打印出来时控制台输出表示该实例处于待定（pending）状态：

```js
let p = new Promise(() => {})
console.log(p) // Promise <pending>)
```

这说明期约是一个有状态的对象，可能处于如下 3 种状态之一：

- 待定（pending）：表示尚未开始或者正在执行中
- 兑现（fulfilled）：表示已经成功完成，有时也称为解决（resolved）
- 拒绝（rejected）：表示没有成功完成

期约的状态代表期约是否完成。待定（ pending）是期约的最初始状态。在待定状态下，期约可以落定（ settled）为代表成功的兑现（ fulfilled）状态，或者代表失败的拒绝（ rejected）状态。无论落定为哪种状态都是不可逆的，但是转换为兑现或拒绝并不能保证期约必然会脱离待定状态。

某些情况下，这个状态机就是期约可以提供的最有用的信息。在代码中能够得知异步代码已经完成是很重要的信息，比如：期约要向服务器发送一个 HTTP 请求，请求返回 200~299 范围内的状态码就足以让期约的状态变为“兑现”。类似地，如果请求返回的状态码不在 200~299 这个范围内，那么就会把期约状态切换为“拒绝”。

在另外一些情况下，期约封装的异步操作会实际生成某个值，而程序期待期约状态改变时可以访问这个值。相应地，如果期约被拒绝，程序就会期待期约状态改变时可以拿到拒绝的理由。比如，假设期约向服务器发送一个 HTTP 请求并预定会返回一个 JSON，如果请求返回范围在 200~299 的状态码，则足以让期约的状态变为兑现。此时期约内部就可以收到一个 JSON 字符串。类似地，如果请求返回的状态码不在 200~299 这个范围内，那么就会把期约状态切换为拒绝。此时拒绝的理由可能是一个 Error 对象，包含着 HTTP 状态码及相关错误消息。

为了支持这两种用例，每个期约只要状态切换为兑现，就会有一个私有的内部值（ value）。类似地，每个期约只要状态切换为拒绝，就会有一个私有的内部理由（ reason）。无论是值还是理由，都是包含原始值或对象的不可修改的引用。二者都是可选的，而且默认值为 undefined。在期约到达某个落定状态时执行的异步代码始终会收到这个值或理由。

### 3.2 执行器函数

**期约的状态是私有的，不能直接通过 JavaScript 检测到，而且期约的状态也不能被外部 JavaScript 代码修改**，这样做才能有效隔离外部的同步代码。也因此只能在期约的执行器函数中完成状态改变。执行器函数主要有两项职责：初始化期约的异步行为和控制状态的最终转换。其中，控制期约状态的转换是
通过调用它的两个函数参数实现的。这两个函数参数通常都命名为 resolve()和 reject()。调用 resolve()会把状态切换为兑现，调用 reject()会把状态切换为拒绝。另外，调用 reject()也会抛出错误。

状态转换为解决：

```js
let p = new Promise((resolve, reject) => {
  resolve()
})
setTimeout(console.log, 0, p) // Promise {<fulfilled>: undefined}
```

状态转换为拒绝：

```js
let p = new Promise((resolve, reject) => {
  reject()
})
setTimeout(console.log, 0, p) // 报错Promise {<rejected>: undefined}
```

无论 resolve()和 reject()中的哪个被调用，状态转换都不可撤销了。于是继续修改状态会静默失败，如下所示：

```js
let p = new Promise((resolve, reject) => {
  resolve()
  reject() // 没有效果
})
setTimeout(console.log, 0, p) // Promise <resolved>
```

为避免期约卡在待定状态，可以添加一个定时退出功能。比如，可以通过 setTimeout 设置一个 10 秒钟后无论如何都会拒绝期约的回调：

```js
let p = new Promise((resolve, reject) => {
  setTimeout(reject, 10000) // 10 秒后调用 reject()
  // 执行函数的逻辑
})
setTimeout(console.log, 0, p) // Promise <pending>
setTimeout(console.log, 11000, p) // 11 秒后再检查状态
// (After 10 seconds) Uncaught error
// (After 11 seconds) Promise <rejected>
```

因为期约的状态只能改变一次，所以这里的超时拒绝逻辑中可以放心地设置让期约处于待定状态的最长时间。如果执行器中的代码在超时之前已经解决或拒绝，那么超时回调再尝试拒绝也会静默失败。

### 3.3 同步/异步执行的二元性

```js
try {
  throw new Error('foo')
} catch (e) {
  console.log(e) // Error: foo
}

// Uncaught (in promise) Error: bar
try {
  Promise.reject(new Error('bar'))
} catch (e) {
  console.log(e)
}
```

第一个 try/catch 抛出并捕获了错误，第二个 try/catch 抛出错误却没有捕获到，因为后者没有通过异步模式捕获错误。从这里可以看出期约真正的异步特性：它们是同步对象（在同步执行模式中使用），但也是异步执行模式的媒介。

代码一旦开始以异步模式执行，则唯一与之交互的方式就是使用异步结构——更具体地说，就是期约的方法。

## 四 Promise 对象的静态方法

### 4.1 Promise.resolve()

除了执行器函数可以转换为落定状态，通过调用 Promise.resolve() 静态方法，也可以实例化一个解决的期约：

```js
// 二者没有区别
let p1 = new Promise((resolve, reject) => resolve())
let p2 = Promise.resolve()
```

这个解决的期约的值对应着传给 Promise.resolve()的第一个参数。使用这个静态方法，实际上可以把任何值都转换为一个期约：

```js
setTimeout(console.log, 0, Promise.resolve()) // Promise <resolved>: undefined
setTimeout(console.log, 0, Promise.resolve(3)) // Promise <resolved>: 3

// 多余的参数会忽略
setTimeout(console.log, 0, Promise.resolve(4, 5, 6)) // Promise <resolved>: 4
```

如果传入的参数本身是一个期约，那它的行为就类似于一个空包装。因此，Promise.resolve() 可以说是一个幂等方法，如下所示：

```js
let p = Promise.resolve(7)
setTimeout(console.log, 0, p === Promise.resolve(p)) // true

setTimeout(console.log, 0, p === Promise.resolve(Promise.resolve(p))) // true
```

这个幂等性会保留传入期约的状态：

```js
let p = new Promise(() => {})
setTimeout(console.log, 0, p) // Promise <pending>
setTimeout(console.log, 0, Promise.resolve(p)) // Promise <pending>
setTimeout(console.log, 0, p === Promise.resolve(p)) // true
```

这个静态方法能够包装任何非期约值，包括错误对象，并将其转换为解决的期约。因此，也可能导致不符合预期的行为：

```js
let p = Promise.resolve(new Error('foo'))
setTimeout(console.log, 0, p) // Promise <resolved>: Error: foo
```

### 4.2 Promise.reject()

Promise.reject() 会实例化一个拒绝的期约并抛出一个异步错误（这个错误不能通过 try/catch 捕获，而只能通过拒绝处理程序捕获）。下面的两个期约实例实际上是一样的：

```js
let p1 = new Promise((resolve, reject) => reject())
let p2 = Promise.reject()
```

这个拒绝的期约的理由就是传给 Promise.reject() 的第一个参数。这个参数也会传给后续的拒绝处理程序：

```js
let p = Promise.reject(3)
setTimeout(console.log, 0, p) // Promise <rejected>: 3
p.then(null, (e) => setTimeout(console.log, 0, e)) // 3
```

注意：Promise.reject() 并没有照搬 Promise.resolve() 的幂等逻辑。如果给它传一个期约对象，则这个期约会成为它返回的拒绝期约的理由：

```js
// Promise <rejected>: Promise <resolved>
setTimeout(console.log, 0, Promise.reject(Promise.resolve()))
```

### 4.3 Promise 其他 API

期约还有一些连锁反应相关的 API，如： `Promise.all()` 见下一节

## 五 Promise 的连锁反应

### 5.1 期约连锁

多个期约组合在一起可以构成强大的代码逻辑。这种组合可以通过两种方式实现：期约连锁与期约合成。前者就是一个期约接一个期约地拼接，后者则是将多个期约组合为一个期约。

把期约逐个地串联起来是一种非常有用的编程模式。之所以可以这样做，是因为每个期约实例的方法（ then()、 catch()和 finally()）都会返回一个新的期约对象，而这个新期约又有自己的实例方法。这样连缀方法调用就可以构成所谓的“期约连锁”。比如：

```js
let p = new Promise((resolve, reject) => {
  console.log('first')
  resolve()
})
p.then(() => console.log('second'))
  .then(() => console.log('third'))
  .then(() => console.log('fourth'))
// first
// second
// third
// fourth
```

这个实现最终执行了一连串同步任务。正因为如此，这种方式执行的任务没有那么有用，毕竟分别使用 4 个同步函数也可以做到：

```js
;(() => console.log('first'))()
;(() => console.log('second'))()
;(() => console.log('third'))()
;(() => console.log('fourth'))()
```

要真正执行异步任务，可以改写前面的例子，让每个执行器都返回一个期约实例。这样就可以让每个后续期约都等待之前的期约，也就是串行化异步任务。比如，可以像下面这样让每个期约在一定时间后解决：

```js
let p1 = new Promise((resolve, reject) => {
  console.log('p1 executor')
  setTimeout(resolve, 1000)
})
p1.then(
  () =>
    new Promise((resolve, reject) => {
      console.log('p2 executor')
      setTimeout(resolve, 1000)
    })
)
  .then(
    () =>
      new Promise((resolve, reject) => {
        console.log('p3 executor')
        setTimeout(resolve, 1000)
      })
  )
  .then(
    () =>
      new Promise((resolve, reject) => {
        console.log('p4 executor')
        setTimeout(resolve, 1000)
      })
  )
// p1 executor（ 1 秒后）
// p2 executor（ 2 秒后）
// p3 executor（ 3 秒后）
// p4 executor（ 4 秒后）
```

把生成期约的代码提取到一个工厂函数中，就可以写成这样：

```js
function delayedResolve(str) {
  return new Promise((resolve, reject) => {
    console.log(str)
    setTimeout(resolve, 1000)
  })
}
delayedResolve('p1 executor')
  .then(() => delayedResolve('p2 executor'))
  .then(() => delayedResolve('p3 executor'))
  .then(() => delayedResolve('p4 executor'))
// p1 executor（ 1 秒后）
// p2 executor（ 2 秒后）
// p3 executor（ 3 秒后）
// p4 executor（ 4 秒后）
```

每个后续的处理程序都会等待前一个期约解决，然后实例化一个新期约并返回它。这种结构可以简洁地将异步任务串行化，解决之前依赖回调的难题。假如这种情况下不使用期约，那么前面的代码可能就要这样写了：

```js
function delayedExecute(str, callback = null) {
  setTimeout(() => {
    console.log(str)
    callback && callback()
  }, 1000)
}
delayedExecute('p1 callback', () => {
  delayedExecute('p2 callback', () => {
    delayedExecute('p3 callback', () => {
      delayedExecute('p4 callback')
    })
  })
})
// p1 callback（ 1 秒后）
// p2 callback（ 2 秒后）
// p3 callback（ 3 秒后）
// p4 callback（ 4 秒后）
```

这里其实就解决了回调地狱问题吗，由于 then()、 catch()和 finally()都返回期约，所以串联这些方法也很直观。下面的例子同时使用这 3 个实例方法：

```js
let p = new Promise((resolve, reject) => {
  console.log('initial promise rejects')
  reject()
})
p.catch(() => console.log('reject handler'))
  .then(() => console.log('resolve handler'))
  .finally(() => console.log('finally handler'))
// initial promise rejects
// reject handler
// resolve handler
// finally handler
```

### 5.2 期约图

因为一个期约可以有任意多个处理程序，所以期约连锁可以构建有向非循环图的结构。这样，每个期约都是图中的一个节点，而使用实例方法添加的处理程序则是有向顶点。因为图中的每个节点都会等待前一个节点落定，所以图的方向就是期约的解决或拒绝顺序。

```js
let A = new Promise((resolve, reject) => {
  console.log('A')
  resolve()
})
let B = A.then(() => console.log('B'))
let C = A.then(() => console.log('C'))
B.then(() => console.log('D'))
B.then(() => console.log('E'))
C.then(() => console.log('F'))
C.then(() => console.log('G'))
// A
// B
// C
// D
// E
// F
// G
```

注意，日志的输出语句是对二叉树的层序遍历。如前所述，期约的处理程序是按照它们添加的顺序执行的。由于期约的处理程序是先添加到消息队列， 然后才逐个执行，因此构成了层序遍历。树只是期约图的一种形式。考虑到根节点不一定唯一，且多个期约也可以组合成一个期约（通过下一节介绍的 Promise.all()和 Promise.race()），所以有向非循环图是体现期约连锁可能性的最准确表达。

### 5.3 Promise.all()

Promise 类提供两个将多个期约实例组合成一个期约的静态方法： Promise.all()和 Promise.race()。而合成后期约的行为取决于内部期约的行为。

Promise.all()静态方法创建的期约会在一组期约全部解决之后再解决。这个静态方法接收一个可迭代对象，返回一个新期约：

```js
let p1 = Promise.all([Promise.resolve(), Promise.resolve()])
// 可迭代对象中的元素会通过 Promise.resolve()转换为期约
let p2 = Promise.all([3, 4])
// 空的可迭代对象等价于 Promise.resolve()
let p3 = Promise.all([])
// 无效的语法
let p4 = Promise.all()
// TypeError: cannot read Symbol.iterator of undefined
```

合成的期约只会在每个包含的期约都解决之后才解决：

```js
let p = Promise.all([
  Promise.resolve(),
  new Promise((resolve, reject) => setTimeout(resolve, 1000)),
])
setTimeout(console.log, 0, p) // Promise <pending>
p.then(() => setTimeout(console.log, 0, 'all() resolved!'))
// all() resolved!（大约 1 秒后）
```

如果至少有一个包含的期约待定，则合成的期约也会待定。如果有一个包含的期约拒绝，则合成的期约也会拒绝：

```js
// 永远待定
let p1 = Promise.all([new Promise(() => {})])
setTimeout(console.log, 0, p1) // Promise <pending>
// 一次拒绝会导致最终期约拒绝
let p2 = Promise.all([Promise.resolve(), Promise.reject(), Promise.resolve()])
setTimeout(console.log, 0, p2) // Promise <rejected>
// Uncaught (in promise) undefined
```

如果所有期约都成功解决，则合成期约的解决值就是所有包含期约解决值的数组，按照迭代器顺序：

```js
let p = Promise.all([Promise.resolve(3), Promise.resolve(), Promise.resolve(4)])
p.then((values) => setTimeout(console.log, 0, values)) // [3, undefined, 4]
```

如果有期约拒绝，则第一个拒绝的期约会将自己的理由作为合成期约的拒绝理由。之后再拒绝的期约不会影响最终期约的拒绝理由。不过，这并不影响所有包含期约正常的拒绝操作。合成的期约会静默处理所有包含期约的拒绝操作，如下所示：

```js
// 虽然只有第一个期约的拒绝理由会进入
// 拒绝处理程序，第二个期约的拒绝也
// 会被静默处理，不会有错误跑掉
let p = Promise.all([
  Promise.reject(3),
  new Promise((resolve, reject) => setTimeout(reject, 1000)),
])
p.catch((reason) => setTimeout(console.log, 0, reason)) // 3
// 没有未处理的错误
```

### 5.4 Promise.race()

Promise.race()静态方法返回一个包装期约，是一组集合中最先解决或拒绝的期约的镜像。这个方法接收一个可迭代对象，返回一个新期约：

```js
let p1 = Promise.race([Promise.resolve(), Promise.resolve()])
// 可迭代对象中的元素会通过 Promise.resolve()转换为期约
let p2 = Promise.race([3, 4])
// 空的可迭代对象等价于 new Promise(() => {})
let p3 = Promise.race([])
// 无效的语法
let p4 = Promise.race()
// TypeError: cannot read Symbol.iterator of undefined
```

Promise.race()不会对解决或拒绝的期约区别对待。无论是解决还是拒绝，只要是第一个落定的期约， Promise.race()就会包装其解决值或拒绝理由并返回新期约：

```js
// 解决先发生，超时后的拒绝被忽略
let p1 = Promise.race([
  Promise.resolve(3),
  new Promise((resolve, reject) => setTimeout(reject, 1000)),
])
setTimeout(console.log, 0, p1) // Promise <resolved>: 3
// 拒绝先发生，超时后的解决被忽略
let p2 = Promise.race([
  Promise.reject(4),
  new Promise((resolve, reject) => setTimeout(resolve, 1000)),
])
setTimeout(console.log, 0, p2) // Promise <rejected>: 4
// 迭代顺序决定了落定顺序
let p3 = Promise.race([
  Promise.resolve(5),
  Promise.resolve(6),
  Promise.resolve(7),
])
setTimeout(console.log, 0, p3) // Promise <resolved>: 5
```

如果有一个期约拒绝，只要它是第一个落定的，就会成为拒绝合成期约的理由。之后再拒绝的期约不会影响最终期约的拒绝理由。不过，这并不影响所有包含期约正常的拒绝操作。与 Promise.all()类似，合成的期约会静默处理所有包含期约的拒绝操作，如下所示：

```js
// 虽然只有第一个期约的拒绝理由会进入
// 拒绝处理程序，第二个期约的拒绝也
// 会被静默处理，不会有错误跑掉
let p = Promise.race([
  Promise.reject(3),
  new Promise((resolve, reject) => setTimeout(reject, 1000)),
])
p.catch((reason) => setTimeout(console.log, 0, reason)) // 3
// 没有未处理的错误
```

### 5.5 串行期约合成

在异步产生值并传递给处理程序场景下，基于后续期约使用之前期约的返回值来串联期约是期约的基本功能。这很像函数合成，即将多个函数合成为一个函数：

```js
function addTwo(x) {
  return x + 2
}
function addThree(x) {
  return x + 3
}
function addFive(x) {
  return x + 5
}
function addTen(x) {
  return addFive(addTwo(addThree(x)))
}
console.log(addTen(7)) // 17
```

在这个例子中，有 3 个函数基于一个值合成为一个函数。类似地，期约也可以像这样合成起来，渐进地消费一个值，并返回一个结果：

```js
function addTwo(x) {
  return x + 2
}
function addThree(x) {
  return x + 3
}
function addFive(x) {
  return x + 5
}
function addTen(x) {
  return Promise.resolve(x).then(addTwo).then(addThree).then(addFive)
}
addTen(8).then(console.log) // 18
```

使用 Array.prototype.reduce()可以写成更简洁的形式：

```js
function addTwo(x) {
  return x + 2
}
function addThree(x) {
  return x + 3
}
function addFive(x) {
  return x + 5
}
function addTen(x) {
  return [addTwo, addThree, addFive].reduce(
    (promise, fn) => promise.then(fn),
    Promise.resolve(x)
  )
}
addTen(8).then(console.log) // 18
```

这种模式可以提炼出一个通用函数，可以把任意多个函数作为处理程序合成一个连续传值的期约连锁。这个通用的合成函数可以这样实现：

```js
function addTwo(x) {
  return x + 2
}
function addThree(x) {
  return x + 3
}
function addFive(x) {
  return x + 5
}
function compose(...fns) {
  return (x) =>
    fns.reduce((promise, fn) => promise.then(fn), Promise.resolve(x))
}
let addTen = compose(addTwo, addThree, addFive)
addTen(8).then(console.log) // 18
```
